const header = document.querySelector('header')
const body = document.querySelector('main')
const logoutbutton = document.querySelector('.log-out-button')
const list1 = document.querySelector('.list-item1')
const list2 = document.querySelector('.list-item2')
const list3 = document.querySelector('.list-item3')
const nav1 = document.querySelector('.darkmode1')
const nav2 = document.querySelector('.darkmode2')
const nav3 = document.querySelector('.darkmode3')
const nav4 = document.querySelector('.darkmode4')
const icon1 = document.querySelector('.dark1')
const icon2 = document.querySelector('.dark2')
const icon3 = document.querySelector('.dark3')
const icon4 = document.querySelector('.dark4')
const darkmode = document.querySelector('.darkmode')
darkmode.addEventListener('click', () => {
  header.classList.toggle('darkmode')
  body.classList.toggle('darkmode')
  list1.classList.toggle('darkmode')
  list2.classList.toggle('darkmode')
  list3.classList.toggle('darkmode')
  logoutbutton.classList.toggle('darkmode')
  nav1.classList.toggle('darkmode')
  nav2.classList.toggle('darkmode')
  nav3.classList.toggle('darkmode')
  nav4.classList.toggle('darkmode')
  icon1.classList.toggle('darkmode')
  icon2.classList.toggle('darkmode')
  icon3.classList.toggle('darkmode')
  icon4.classList.toggle('darkmode')
})
